### ISSUE TITLE
p80.pool.sks-keyservers.net: Host not found

### ISSUE THREAD

**Issue by obazoud** [st-isidore-de-seville/cookbook-apt-docker#4]
Hi, 

Sometime p80.pool.sks-keyservers.net is not found.
See the following trace.
Is there a way to retry the command or the fallback to another host ?
See also this thread https://github.com/docker/docker/issues/20022

Thanks.

```
[2016-02-22T15:15:27+00:00] INFO: Processing apt_repository[docker-main] action add (apt-docker::default line 23)
[2016-02-22T15:15:27+00:00] INFO: Processing execute[install-key 58118E89F3A912897C070ADBF76221572C52609D] action run (/var/chef/cache/cookbooks/apt/providers/repository.rb line 28)

================================================================================
Error executing action `run` on resource 'execute[install-key 58118E89F3A912897C070ADBF76221572C52609D]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '2'
---- Begin output of apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D ----
STDOUT: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.HKy1L6ekuM --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
STDERR: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
---- End output of apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D ----
Ran apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D returned 2

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/apt/providers/repository.rb

 28:   execute "install-key #{key}" do
 29:     if keyserver.start_with?('hkp://')
 30:       command "apt-key adv --keyserver #{keyserver} --recv #{key}"
 31:     elsif key_proxy.empty?
 32:       command "apt-key adv --keyserver hkp://#{keyserver}:80 --recv #{key}"
 33:     else
 34:       command "apt-key adv --keyserver-options http-proxy=#{key_proxy} --keyserver hkp://#{keyserver}:80 --recv #{key}"
 35:     end
 36:     sensitive new_resource.sensitive if respond_to?(:sensitive)

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/apt/providers/repository.rb:28:in `install_key_from_keyserver'

execute("install-key 58118E89F3A912897C070ADBF76221572C52609D") do
  action [:run]
  retries 0
  retry_delay 2
  default_guard_interpreter :execute
  command "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D"
  backup 5
  returns 0
  declared_type :execute
  cookbook_name "apt-docker"
  not_if { #code block }
end

[2016-02-22T15:15:27+00:00] INFO: Running queued delayed notifications before re-raising exception

================================================================================
Error executing action `add` on resource 'apt_repository[docker-main]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
execute[install-key 58118E89F3A912897C070ADBF76221572C52609D] (/var/chef/cache/cookbooks/apt/providers/repository.rb line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D ----
STDOUT: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.HKy1L6ekuM --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
STDERR: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
---- End output of apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D ----
Ran apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 58118E89F3A912897C070ADBF76221572C52609D returned 2

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/apt-docker/recipes/default.rb

 23:   apt_repository repo do
 24:     # define all attributes even though we are not using them all so that the
 25:     #  values can be passed through to override apt repository definitions
 26: 
 27:     # Attribute Sources:
 28:     #  https://github.com/opscode-cookbooks/apt
 29:     #  https://github.com/opscode-cookbooks/apt/blob/master/resources/repository.rb
 30: 
 31:     repo_name value['repo_name'] if value['repo_name']
 32:     uri value['uri'] if value['uri']
 33:     distribution value['distribution'] if value['distribution']
 34:     components value['components'] if value['components']
 35:     arch value['arch'] if value['arch']
 36:     trusted value['trusted'] if value['trusted']
 37:     deb_src value['deb-src'] if  value['deb-src']
 38:     keyserver value['keyserver'] if value['keyserver']
 39:     key value['key'] if value['key']
 40:     key_proxy value['key_proxy'] if value['key_proxy']
 41:     cookbook value['cookbook'] if value['cookbook']
 42:     cache_rebuild value['cache_rebuild'] if value['cache_rebuild']
 43:   end if value['managed']
 44: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/apt-docker/recipes/default.rb:23:in `block in from_file'

apt_repository("docker-main") do
  action :add
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :apt_repository
  cookbook_name "apt-docker"
  recipe_name "default"
  uri "https://apt.dockerproject.org/repo"
  distribution "ubuntu-trusty"
  components ["main"]
  keyserver "hkp://p80.pool.sks-keyservers.net:80"
  key "58118E89F3A912897C070ADBF76221572C52609D"
  cache_rebuild true
end

[2016-02-22T15:15:27+00:00] INFO: Running queued delayed notifications before re-raising exception
```

**Comment by Fitzsimmons** [comment]
You can manually override the keyserver attribute by setting `node.override['apt-docker']['repos']['docker-main']['keyserver']` (or set it in a role, environment, etc.)

If you have a less restrictive firewall, you can use `hkp://ha.pool.sks-keyservers.net`, which is a high availability pool hosted by sks-keyservers, which should not suffer from the frequent outages that are common for the port80 pool. If you are behind a restrictive firewall, you may have success with `hkp://keyserver.ubuntu.com:80` instead.
